In [2]:
poleras = [254, 203, 182, 50];

meses = ["Ene", "Feb", "Mar", "Abri"];
print(poleras);
print ("");
meses



[254, 203, 182, 50]



['Ene', 'Feb', 'Mar', 'Abri']

In [3]:
poleras * 2 # solo muestra dos veces la matriz o lista, no la opera

[254, 203, 182, 50, 254, 203, 182, 50]

In [4]:
import numpy as np
array_poleras = np.array(poleras) # Llamar matriz en formato de vector o arreglo
#para poder manipular la matriz
array_poleras


array([254, 203, 182,  50])

In [5]:
array_poleras * 2

array([508, 406, 364, 100])

In [6]:
#Logaritmo de 5
np.log(5)

1.6094379124341003

In [7]:
np.log(5)+ np.pi / np.sqrt(5) - np.exp(2)

-4.374655240288405

In [8]:
np.sqrt(5) - np.exp(2)

-5.152988121430861

In [9]:
# Si no quiero importar numpy

from numpy import log10 as mylog10

mylog10(1000)

3.0

In [10]:
print(np.array(poleras+meses))

['254' '203' '182' '50' 'Ene' 'Feb' 'Mar' 'Abri']


In [11]:
lista = np.array([1,2,3,4,5,6,78,9])
print(lista[0:2])
print(lista[2:4])
print(lista[4:6])

[1 2]
[3 4]
[5 6]


In [24]:
arr = np.arange(5) # Imprime rango de la posición 1 al 5
arr

array([0, 1, 2, 3, 4])

In [25]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [29]:
print(arr[0], arr[2:4],arr[-1]) # El último por ser negativo hace el conteo de atraz hacia adelante
print(arr[:4]) # No es necesario escribor 0:4, el espacio vacio se entiende como 0

0 [2 3] 4
[0 1 2 3]


In [30]:
np.random.seed(2022) #Para reproducibilidad en Numpy
estaturas = np.random.normal(loc=160, scale=5, size=10000)#loc para la media, 
#scale es la desviación estandar y size es el tamaño
estaturas

array([159.9973605 , 158.62549288, 159.30357219, ..., 161.55546995,
       160.34955216, 158.77472458])

In [32]:
estaturas > 159 # Genera un resultado booleano, notar que el primer valor del array
# anterior es mayor a 159, el segundo menor, el tercero mayor, por eso los resultados
#True o False

array([ True, False,  True, ...,  True,  True, False])

In [33]:
cond1 = estaturas > 159
cond2 = estaturas < 161
print(estaturas[cond1 & cond2]) # estaturas en el rango de [159,161] # Otros operadores != 
# no ~, o


[159.9973605  159.30357219 159.54893404 ... 160.55780521 160.29742514
 160.34955216]


In [43]:
cond3 = estaturas > 175
print (estaturas[cond3])

[177.34539691 175.84361724 175.46177658 177.14862666 175.96289987
 176.8307282  175.23806396 175.3929571  180.21385542 176.50448403
 177.05879804 175.7990716  175.55682641 175.64145803 175.87669112]


In [44]:
print (estaturas[(estaturas > 175)]) # Otra forma de conseguir el mismo resultado

[177.34539691 175.84361724 175.46177658 177.14862666 175.96289987
 176.8307282  175.23806396 175.3929571  180.21385542 176.50448403
 177.05879804 175.7990716  175.55682641 175.64145803 175.87669112]


In [45]:
80-25
# rango es la diferencia entre el max y el min

55

**Estadística descriptiva**


| Sintaxis	| Descripcion |
|-----------|-------------|
min() |	Minimo
max()	| Maximo
ptp()	| Rango
quantile(a, q)	| Cuantil q
median(a)	| Mediana
mean()	| Promedio
std()	| Desviacion Standard
var()	| Varianza

In [49]:
print("Promedio :", np.mean(estaturas[estaturas > 175]))
print("Varianza :", np.var(estaturas))
print("Percentil 75:", np.quantile(estaturas, 0.75) )

Promedio : 176.39168341105568
Varianza : 24.76954640993701
Percentil 75: 163.36988703738757


In [50]:
np.mean(estaturas) # Obtiene la media de todos los datos

160.00986868635252

In [56]:
def fahrenheit_a_celcius(temperatura):
    calculo = (temperatura - 32) / 1.8
    return calculo

In [57]:
temperaturas_fahrenheit = np.array([32,20,62,86])
fahrenheit_a_celcius(temperaturas_fahrenheit)

array([ 0.        , -6.66666667, 16.66666667, 30.        ])

In [58]:
notas = np.array([2.5, 7, 1.4, 6.8, 5, 4.9, 5.8])
notas

array([2.5, 7. , 1.4, 6.8, 5. , 4.9, 5.8])

In [59]:
estado_aprobacion = np.where (notas >=4, "Aprobado", "Reprobado")
estado_aprobacion

array(['Reprobado', 'Aprobado', 'Reprobado', 'Aprobado', 'Aprobado',
       'Aprobado', 'Aprobado'], dtype='<U9')

In [68]:
# np.select
estado_examen = np.select(
    # Condiciones
    condlist = [notas > 5.5 , notas >= 4.0],
    # Elecciones
    choicelist = ["Eximido", "A dar el examen"],
    #Else
    default = "A salvar el ramo",
)
estado_examen

array(['A salvar el ramo', 'Eximido', 'A salvar el ramo', 'Eximido',
       'A dar el examen', 'A dar el examen', 'Eximido'], dtype='<U16')

In [70]:
np.random.seed(2022)
mat = np.random.randint(low=0, high=10, size=(3,4))
print(mat)

[[0 1 1 0]
 [7 8 2 8]
 [0 5 9 1]]


In [71]:
print("Una matriz:\n", mat)
print("")
print("Un elemento:", mat[1, 2]) # filas x columnas = FELIZ CUMPLEAÑOS!!!!!!
print("")
print("Una fila:", mat[1 , :])
print("")
print("Una columna:", mat[:, 1])
print("")
print("Un subconjunto:\n", mat[0:2, 1:4]) #filas 0 y 1, además de columnas 1, 2 y 3 

Una matriz:
 [[0 1 1 0]
 [7 8 2 8]
 [0 5 9 1]]

Un elemento: 2

Una fila: [7 8 2 8]

Una columna: [1 8 5]

Un subconjunto:
 [[1 1 0]
 [8 2 8]]


Repasar el PPT y hacer el Ejercicio